{
  "status": "\u23f3 running",
  "phase": "running",
  "pid": null,
  "started": 1761613193,
  "elapsed": 6,
  "csv": "DSNdata/data_20250331_20251130.csv",
  "csv_raw": "https://raw.githubusercontent.com/soazcomms/soazcomms.github.io/main/DSNdata/data_20250331_20251130.csv",
  "csv_size": 34,
  "log": "logs/csv-DSN019-S_MtLemmon-20250331-20251130.log",
  "log_tail": " 2 files changed, 8 insertions(+), 3 deletions(-)\nTo https://github.com/soazcomms/soazcomms.github.io\n   63faacba..5543dbce  main -> main\n{\"status\": \"\\u2705 CSV ready for DSN019-S_MtLemmon 20250331-20251130\", \"csv\": \"https://soazcomms.github.io/DSNdata/data_20250331_20251130.csv\", \"csv_raw\": \"https://raw.githubusercontent.com/soazcomms/soazcomms.github.io/main/DSNdata/data_20250331_20251130.csv\", \"timestamp\": 1761607616}\n[2025-10-27 17:02:20] CSV job start for DSN019-S_MtLemmon 2025-03-31..2025-11-30\n[2025-10-27 17:41:11] CSV job start for DSN019-S_MtLemmon 2025-03-31..2025-11-30\n[2025-10-27 17:47:42] CSV job start for DSN019-S_MtLemmon 2025-03-31..2025-11-30\n[2025-10-28T00:57:28Z] CSV job start for DSN019-S_MtLemmon 2025-03-31..2025-11-30\n[2025-10-28T00:57:29Z] Running: python3 /Users/soazdsn/DSN/DSNcode/DSN_generate_csv.py --label DSN019-S_MtLemmon --from 2025-03-31 --to 2025-11-30 --site-repo /Users/soazdsn/DSN/soazcomms.github.io --out /Users/soazdsn/DSN/soazcomms.github.io/DSNdata/data_20250331_20251130.csv\nTraceback (most recent call last):\n  File \"/Users/soazdsn/DSN/DSNcode/DSN_generate_csv.py\", line 104, in <module>\n    run([\"git\",\"reset\",\"--hard\"], cwd=repo, check=False)\nNameError: name 'repo' is not defined. Did you mean: 'repr'?\n[2025-10-28T00:57:35Z] ERROR rc=1\n[2025-10-28T00:59:53Z] CSV job start for DSN019-S_MtLemmon 2025-03-31..2025-11-30\n[2025-10-28T00:59:54Z] Running: python3 /Users/soazdsn/DSN/DSNcode/DSN_generate_csv.py --label DSN019-S_MtLemmon --from 2025-03-31 --to 2025-11-30 --site-repo /Users/soazdsn/DSN/soazcomms.github.io --out /Users/soazdsn/DSN/soazcomms.github.io/DSNdata/data_20250331_20251130.csv\nusage: DSN_generate_csv.py [-h] --label LABEL --from FROM_DATE --to TO_DATE\n                           [--site-repo SITE_REPO] [--source SOURCE]\n                           [--cmd CMD]\nDSN_generate_csv.py: error: unrecognized arguments: --out /Users/soazdsn/DSN/soazcomms.github.io/DSNdata/data_20250331_20251130.csv\n",
  "rc": null,
  "note": null,
  "timestamp": 1761613199
}